### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by chill-otter** [leichain/crypto-coven-test#6]
## Checklist

- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

![Screenshot_2022-08-10-00-34-20-153_org telegram messenger](https://user-images.githubusercontent.com/61946705/184652722-eee465dc-e74a-4f2e-acdd-f35e7818cd5d.jpg)

How to Fix this Issue can you help

__Originally posted by @niranjantechofficial in https://github.com/ytdl-org/youtube-dl/issues/31171__

**Comment by dirkf** [comment]
Actually, in https://github.com/ytdl-org/youtube-dl/issues/31148.

**Comment by niranjantechofficial** [comment]
What we need to do to fix that issue
